- name: Deploy application, create service, scale application
  hosts: localhost
  user: ubuntu
  become: yes

  vars:
    myPath: "/home/ubuntu"

  tasks:
  - name: 1. Update Package Manager
    apt:
      update_cache: yes

  - name: 2. Create Deployment
    become: no
    shell:
      cmd: kubectl create deployment cw2deployment --image=docker.io/michaeljmckenna/coursework2:1.0

  - name: 3. Create Service
    become: no
    shell:
      cmd: kubectl expose deployment/cw2deployment --"NodePort" --port 8080 --name np-service

  - name: 4. Scale Deployments
    become: no
    shell:
      cmd: kubctl scale deployments/cw2deployment --replicas=4


